# Generated by Django 5.2 on 2025-05-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_itempedido_delete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='numero_mesa',
        ),
        migrations.AddField(
            model_name='pedido',
            name='mesa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='retirada',
            field=models.BooleanField(default=False),
        ),
    ]
