# Generated by Django 5.2 on 2025-05-22 18:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_remove_pedido_numero_mesa_pedido_mesa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pedido_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
